version: '3.4'

services:

 api-server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db_service

 db_service:
   image: mysql:5.7.8
   restart: always
   environment:
     - MYSQL_ROOT_PASSWORD=root
   ports:
     - 3306:3306
   command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']




